apiVersion: v1
kind: Service
metadata:
  name: capstone-api

spec:
  selector:
    app: capstone-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-api
  template:
    metadata:
      labels:
        app: capstone-api
    spec:
      containers:
        - name: capstone-api
          image: ceoehis/header-parser-microservice:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080